// Generated by CoffeeScript 1.9.3
$.fn.col_format = function() {
  var children, cl, i, s;
  s = void 0;
  children = $(this).children();
  cl = children.length;
  if ($(this).hasClass('row') === true) {
    i = 0;
    while (i < cl) {
      if (cl === 1) {
        s = 12;
      } else if (cl === 2) {
        s = 6;
      } else if (cl === 3) {
        s = 4;
      } else if (cl === 4) {
        s = 3;
      } else if (cl > 4) {
        s = 12;
      }
      if ($(children[i]).hasClass('col') === true) {
        $(children[i]).toggleClass('col-md-' + s);
        $(children[i]).toggleClass('col');
      }
      i++;
    }
  }
  return cl + ' | ' + s;
};
